# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import blockchain_pb2 as protos_dot_blockchain__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/blockchain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BlockchainNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTransaction = channel.unary_unary(
                '/blockchain.BlockchainNode/SubmitTransaction',
                request_serializer=protos_dot_blockchain__pb2.Transaction.SerializeToString,
                response_deserializer=protos_dot_blockchain__pb2.Ack.FromString,
                _registered_method=True)
        self.BroadcastBlock = channel.unary_unary(
                '/blockchain.BlockchainNode/BroadcastBlock',
                request_serializer=protos_dot_blockchain__pb2.Block.SerializeToString,
                response_deserializer=protos_dot_blockchain__pb2.Ack.FromString,
                _registered_method=True)
        self.BroadcastTransaction = channel.unary_unary(
                '/blockchain.BlockchainNode/BroadcastTransaction',
                request_serializer=protos_dot_blockchain__pb2.Transaction.SerializeToString,
                response_deserializer=protos_dot_blockchain__pb2.Ack.FromString,
                _registered_method=True)


class BlockchainNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitTransaction(self, request, context):
        """Client submits a transaction to a node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BroadcastBlock(self, request, context):
        """Node broadcasts a new block to other nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BroadcastTransaction(self, request, context):
        """Node broadcasts a pending transaction to other nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlockchainNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTransaction,
                    request_deserializer=protos_dot_blockchain__pb2.Transaction.FromString,
                    response_serializer=protos_dot_blockchain__pb2.Ack.SerializeToString,
            ),
            'BroadcastBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastBlock,
                    request_deserializer=protos_dot_blockchain__pb2.Block.FromString,
                    response_serializer=protos_dot_blockchain__pb2.Ack.SerializeToString,
            ),
            'BroadcastTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastTransaction,
                    request_deserializer=protos_dot_blockchain__pb2.Transaction.FromString,
                    response_serializer=protos_dot_blockchain__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blockchain.BlockchainNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('blockchain.BlockchainNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BlockchainNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blockchain.BlockchainNode/SubmitTransaction',
            protos_dot_blockchain__pb2.Transaction.SerializeToString,
            protos_dot_blockchain__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BroadcastBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blockchain.BlockchainNode/BroadcastBlock',
            protos_dot_blockchain__pb2.Block.SerializeToString,
            protos_dot_blockchain__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BroadcastTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blockchain.BlockchainNode/BroadcastTransaction',
            protos_dot_blockchain__pb2.Transaction.SerializeToString,
            protos_dot_blockchain__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
