# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/blockchain.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/blockchain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protos/blockchain.proto\x12\nblockchain\"^\n\x0bTransaction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x02\x12\x11\n\ttimestamp\x18\x05 \x01(\x01\"\xb2\x01\n\x05\x42lock\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x15\n\rprevious_hash\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\x12-\n\x0ctransactions\x18\x04 \x03(\x0b\x32\x17.blockchain.Transaction\x12\r\n\x05nonce\x18\x05 \x01(\x05\x12\x0c\n\x04hash\x18\x06 \x01(\t\x12\x10\n\x08miner_id\x18\x07 \x01(\t\x12\x12\n\ndifficulty\x18\x08 \x01(\x05\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xcd\x01\n\x0e\x42lockchainNode\x12?\n\x11SubmitTransaction\x12\x17.blockchain.Transaction\x1a\x0f.blockchain.Ack\"\x00\x12\x36\n\x0e\x42roadcastBlock\x12\x11.blockchain.Block\x1a\x0f.blockchain.Ack\"\x00\x12\x42\n\x14\x42roadcastTransaction\x12\x17.blockchain.Transaction\x1a\x0f.blockchain.Ack\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.blockchain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTION']._serialized_start=39
  _globals['_TRANSACTION']._serialized_end=133
  _globals['_BLOCK']._serialized_start=136
  _globals['_BLOCK']._serialized_end=314
  _globals['_ACK']._serialized_start=316
  _globals['_ACK']._serialized_end=355
  _globals['_BLOCKCHAINNODE']._serialized_start=358
  _globals['_BLOCKCHAINNODE']._serialized_end=563
# @@protoc_insertion_point(module_scope)
